version: '3.8'

services:
  # MongoDB service (without authentication)
  mongodb:
    image: mongo:7.0
    container_name: mca-cms-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mca-network

  # Node.js application service
  mca-cms-app:
    build: .
    container_name: mca-cms-app
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - MONGODB_URI=mongodb://mongodb:27017/mca-cms
      - SESSION_SECRET=${SESSION_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-10485760}
    depends_on:
      - mongodb
    volumes:
      - ./public/uploads:${DOCKER_UPLOAD_PATH:-/usr/src/app/public/uploads}
    networks:
      - mca-network

# Define named volumes
volumes:
  mongodb_data:
    driver: local

# Define networks
networks:
  mca-network:
    driver: bridge
